tcp:
  port: 8081

rx:
  ip: 192.168.1.1
  targetIp: 192.168.1.231 # Данный сервер, на который будет отправлена CSI

tx:
  ip: 192.168.1.100
  ifName: wlan0
  dstMacAddr: FF:FF:FF:FF:FF:FF # адрес может быть любым, если Rx является AP
  numOfPacketToSend: 400
  pktIntervalUs: 60000
  pktLen: 512
