rx:
  username: root
  ipAddr: 192.168.1.1
tx:
  username: root
  ipAddr: 192.168.1.100
sendData:
  ifName: wlan0
  dstMacAddr: FF:FF:FF:FF:FF:FF # адрес может быть любым, если Rx является AP
  numOfPacketToSend: 400
  pktIntervalUs: 60000
  pktLen: 512

ttpStaticPath: './build'
tcpPort: 8081
httpPort: 80
websocketPort: 8082
targetIp: 192.168.1.231

smoothOrder: 10 # сглаживание амплитудных значений
csiLocalRepoMaxCount: 1000
datFilePath: 'logs/'
ProcessorRounder: 3

filter:
  payloadLen:
    min: 500
    max: 1800
  nr: 2
  nc: 2
  nTones: 56
