tcpPort: 8081
rxIp: 192.168.1.1
txIp: 192.168.1.100
targetIp: 192.168.1.231

ifName: wlan0
dstMacAddr: FF:FF:FF:FF:FF:FF # адрес может быть любым, если Rx является AP
numOfPacketToSend: 400
pktIntervalUs: 60000
pktLen: 512

filterOrder: 10 # фильтрация амплитудных
csiLocalRepoMaxCount: 1000
datFilePath: 'logs/'
ProcessorRounder: 3

filter:
  payloadLen:
    min: 500
    max: 1800
  nr: 2
  nc: 2
  nTones: 56
